name: TokenMenyu
options:
  deploymentTarget:
    macOS: "14.0"
targets:
  TokenMenyu:
    type: application
    platform: macOS
    sources:
      - Sources/TokenMenyu
      - AppIcon.icns
    settings:
      PRODUCT_NAME: TokenMenyu
      PRODUCT_BUNDLE_IDENTIFIER: com.lodev09.tokenmenyu
      MARKETING_VERSION: 1.4.0
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_IDENTITY: "-"
      SWIFT_VERSION: "5.0"
    scheme:
      testTargets: []
